title: CS6038/CS5138 Malware Analysis, UC
theme: jekyll-theme-hacker
show_downloads: false
repository: ckane/CS7038-Malware-Analysis
twitter_username: colemankane
github_username: ckane
description: Course content for UC Malware Analysis
markdown: kramdown
