title: CS6038/CS5138 Malware Analysis, UC
theme: jekyll-theme-hacker
show_downloads: false
repository: ckane/CS7038-Malware-Analysis
twitter_username: colemankane
github_username: ckane
description: Course content for UC Malware Analysis
markdown: kramdown
explore_topics:
  - acrobat
  - android
  - apk
  - asm
  - cfg
  - c
  - clamav
  - debugger
  - decompilation
  - disassembly
  - dynamic
  - editing
  - exiftool
  - ffdec
  - gdb
  - ghidra
  - immunity-debugger
  - inetsim
  - java
  - metasploit
  - mobile
  - mongodb
  - msoffice
  - objdump
  - ole
  - patching
  - pdf
  - pdfparser
  - python
  - rtf
  - run-time-analysis
  - strings
  - sysmon
  - virtualbox
  - virustotal
  - vm
  - vscan
  - x86-64
  - x86
  - yara
collections:
  tags:
    layout: tag
    output: true
    permalink: /:collection/:name
